version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: ydc-backend
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/data:/app/data
      - ./backend/images:/app/images
      - ./backend/config:/app/config:ro
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: ydc-frontend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  backend-data:
  backend-images:


